- hosts: db
  #user: vagrant

  tasks:
  - action: shell whoami
    register: whoami

  - name: set locale
    shell: export LC_ALL="en_US.UTF-8" && export LANGUAGE="en_US.UTF-8" && locale >> /etc/environment 
    sudo: yes

  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600
    sudo: yes

  - name: install packages
    apt: pkg={{ item }} state=latest force=yes
    sudo: yes
    with_items:
      - mongodb
      - curl
      - gnupg
      - fail2ban
      - ufw
      - wget
      - rsync
      - psmisc
      - chkrootkit

  - name: ensure fail2ban is running
    sudo: yes
    action: service name=fail2ban state=restarted enabled=yes

  - name: forbid SSH root login
    sudo: yes
    lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify: restart ssh

  - name: reset firewall
    sudo: yes
    action: shell ufw --force reset

  - name: allow firewall authorized ports
    sudo: yes
    action: shell ufw allow {{ item }}
    with_items:
      - 22
      - 27017

  - name: enable firewall
    sudo: yes
    action: shell ufw --force enable

  - name: open port mongodb to access
    replace: dest=/etc/mongodb.conf regexp='#port = 27017' replace='port = 27017'
    sudo: yes

  - name: bind ip to access mongodb from app
    replace: dest=/etc/mongodb.conf regexp='bind_ip = 127.0.0.1' replace='bind_ip = 127.0.0.1,192.168.1.5'
    sudo: yes
    notify: restart mongodb

  handlers:
  - name: restart ssh
    sudo: yes
    action: service name=ssh state=restarted enabled=yes

  - name: restart mongodb
    action: service name=mongodb state=restarted enabled=yes
    sudo: yes
